{$ include 'pygfx.std.wgsl' $}
{$ include 'pygfx.colormap.wgsl' $}
{$ include 'pygfx.image_sample.wgsl' $}
{$ include 'pygfx.light_phong_simple.wgsl' $}
// NOTE: do NOT include 'pygfx.volume_common.wgsl' — we bypass get_vol_geometry().

// ── Constants ──────────────────────────────────────────────────────────────
const BORDER: f32          = 3.0;     // ghost border width in voxels
const MAX_BRICK_ITERS: u32 = 512u;   // outer loop guard
const STEPS_PER_BRICK: f32 = 24.0;   // target inner steps across a full brick

// Varyings are auto-generated by pygfx's VaryingResolver from assignments
// in vs_main. Do NOT define a struct Varyings here.


// ── Block-scale lookup ────────────────────────────────────────────────────
// u_block_scales.scale_k = downscale factor relative to finest level.
// k=0 always [1,1,1]. k=1 might be [2,2,2] (isotropic) or [1,1,2] (z-only).
// The w channel of the LUT stores level index (1-based: 0 = unloaded).
fn get_lod_scale(lut_w: u32) -> vec3<f32> {
    // lut_w is 1-based (0 = unloaded). scale_k is stored at index k in Python.
    // lut_w=1 (finest) → scale_1, lut_w=2 → scale_2, etc.
    switch lut_w {
        case 1u:  { return u_block_scales.scale_1.xyz; }
        case 2u:  { return u_block_scales.scale_2.xyz; }
        case 3u:  { return u_block_scales.scale_3.xyz; }
        case 4u:  { return u_block_scales.scale_4.xyz; }
        case 5u:  { return u_block_scales.scale_5.xyz; }
        case 6u:  { return u_block_scales.scale_6.xyz; }
        case 7u:  { return u_block_scales.scale_7.xyz; }
        case 8u:  { return u_block_scales.scale_8.xyz; }
        case 9u:  { return u_block_scales.scale_9.xyz; }
        default:  { return u_block_scales.scale_1.xyz; }
    }
}


// ── LOD debug colour ──────────────────────────────────────────────────────
fn get_lod_color(lut_w: u32) -> vec3<f32> {
    switch lut_w {
        case 0u:  { return vec3<f32>(0.0, 0.0, 0.0); }   // unloaded
        case 1u:  { return vec3<f32>(0.0, 1.0, 0.0); }   // finest — green
        case 2u:  { return vec3<f32>(0.5, 1.0, 0.0); }   // yellow-green
        case 3u:  { return vec3<f32>(1.0, 1.0, 0.0); }   // yellow
        case 4u:  { return vec3<f32>(1.0, 0.5, 0.0); }   // orange
        case 5u:  { return vec3<f32>(1.0, 0.0, 0.0); }   // red
        default:  { return vec3<f32>(0.5, 0.0, 0.5); }   // purple
    }
}


// ── Coordinate conversions ────────────────────────────────────────────────

// Normalized space → finest-level voxel space.
// Normalized box: [-normalizedSize/2, +normalizedSize/2]
// Voxel box:      [0, datasetSize)
fn norm_to_voxel(pos: vec3<f32>, norm_size: vec3<f32>, dataset_size: vec3<f32>) -> vec3<f32> {
    return ((pos / norm_size) + 0.5) * dataset_size;
}

fn voxel_to_norm(voxel: vec3<f32>, norm_size: vec3<f32>, dataset_size: vec3<f32>) -> vec3<f32> {
    return (voxel / dataset_size - 0.5) * norm_size;
}


// ── Ray-box intersection ──────────────────────────────────────────────────

// Standard slab test. Returns vec2(tNear, tFar).
// tNear > tFar means miss.
fn intersect_box(
    ray_origin: vec3<f32>, inv_ray_dir: vec3<f32>,
    box_min: vec3<f32>,   box_max: vec3<f32>
) -> vec2<f32> {
    let t0 = (box_min - ray_origin) * inv_ray_dir;
    let t1 = (box_max - ray_origin) * inv_ray_dir;
    let t_near = max(max(min(t0.x, t1.x), min(t0.y, t1.y)), min(t0.z, t1.z));
    let t_far  = min(min(max(t0.x, t1.x), max(t0.y, t1.y)), max(t0.z, t1.z));
    return vec2<f32>(t_near, t_far);
}



// ── Atlas sampling ─────────────────────────────────────────────────────────

// Standard variant: derives pos_in_brick via fmod. Correct for traversal
// where every probe spatially belongs to the brick being sampled.
fn sample_atlas_nearest(
    voxel_pos:  vec3<f32>,   // finest-level voxel coordinates
    lut_entry:  vec4<u32>,   // RGB = slot indices, W = lut_w (level, 1-based)
    lod_scale:  vec3<f32>,   // downscale factor for this level
) -> f32 {
    let block_size  = vec3<f32>(u_vol_params.block_size_x,
                                u_vol_params.block_size_y,
                                u_vol_params.block_size_z);
    let cache_size  = vec3<f32>(u_vol_params.cache_size_x,
                                u_vol_params.cache_size_y,
                                u_vol_params.cache_size_z);
    let padded_size = block_size + vec3<f32>(2.0 * BORDER);

    // Atlas slot base (in texels).
    let tile_origin = vec3<f32>(lut_entry.xyz) * padded_size;

    // Map finest-level voxel → level-k voxel, then take modulo block.
    let voxel_k      = voxel_pos / lod_scale;
    let pos_in_brick = voxel_k - floor(voxel_k / block_size) * block_size;

    // + BORDER: skip ghost border.  + 0.5: sample voxel centre.
    let cache_pos   = tile_origin + pos_in_brick + vec3<f32>(BORDER + 0.5);
    let cache_coord = cache_pos / cache_size;

    return textureSample(t_cache, s_cache, cache_coord).r;
}

// Gradient variant: takes an explicit brick corner (in level-k voxel space)
// instead of re-deriving it via fmod. Use this when the probe may cross a
// brick boundary — fmod would remap it into the wrong tile, producing garbage.
// The sampler's clamp address mode handles the small out-of-border overshoot.
fn sample_atlas_with_corner(
    voxel_pos:     vec3<f32>,   // finest-level voxel coordinates
    lut_entry:     vec4<u32>,   // RGB = slot indices, W = lut_w (level, 1-based)
    lod_scale:     vec3<f32>,   // downscale factor for this level
    brick_corner_k: vec3<f32>,  // anchor brick's corner in level-k voxel space
) -> f32 {
    let block_size  = vec3<f32>(u_vol_params.block_size_x,
                                u_vol_params.block_size_y,
                                u_vol_params.block_size_z);
    let cache_size  = vec3<f32>(u_vol_params.cache_size_x,
                                u_vol_params.cache_size_y,
                                u_vol_params.cache_size_z);
    let padded_size = block_size + vec3<f32>(2.0 * BORDER);

    // Atlas slot base (in texels).
    let tile_origin = vec3<f32>(lut_entry.xyz) * padded_size;

    // Offset from anchor brick corner — allows negative values (ghost below)
    // and values > block_size (ghost above), unlike fmod which always wraps.
    let voxel_k      = voxel_pos / lod_scale;
    let pos_in_brick = voxel_k - brick_corner_k;

    // + BORDER: skip ghost border.  + 0.5: sample voxel centre.
    let cache_pos   = tile_origin + pos_in_brick + vec3<f32>(BORDER + 0.5);
    let cache_coord = cache_pos / cache_size;

    return textureSample(t_cache, s_cache, cache_coord).r;
}

// ── Brick setup ───────────────────────────────────────────────────────────

struct BrickInfo {
    lut_entry:  vec4<u32>,
    lod_scale:  vec3<f32>,
    t_end:      f32,
    num_steps:  u32,
    step_size:  f32,
    brick_max:  f32,
    valid:      bool,
};

fn setup_brick(
    ray_origin:  vec3<f32>,
    ray_dir:     vec3<f32>,
    inv_ray_dir: vec3<f32>,
    t:           f32,
    t_end_ray:   f32,
    norm_size:   vec3<f32>,
    dataset_size: vec3<f32>,
) -> BrickInfo {
    var info: BrickInfo;

    let block_size = vec3<f32>(u_vol_params.block_size_x,
                               u_vol_params.block_size_y,
                               u_vol_params.block_size_z);
    let lut_size_i = vec3<i32>(i32(u_vol_params.lut_size_x),
                               i32(u_vol_params.lut_size_y),
                               i32(u_vol_params.lut_size_z));

    // 1. Current ray position → finest-level voxel → brick index.
    let sample_pos = ray_origin + ray_dir * t;
    let voxel_pos  = clamp(
        norm_to_voxel(sample_pos, norm_size, dataset_size),
        vec3<f32>(0.0),
        dataset_size - vec3<f32>(0.001)
    );
    let brick_f   = floor(voxel_pos / block_size);
    let safe_idx  = clamp(vec3<i32>(brick_f),
                          vec3<i32>(0),
                          lut_size_i - vec3<i32>(1));

    // 2. Brick AABB in normalized space.
    let brick_min_v = brick_f * block_size;
    let brick_max_v = brick_min_v + block_size;
    let brick_min_n = voxel_to_norm(brick_min_v, norm_size, dataset_size);
    let brick_max_n = voxel_to_norm(brick_max_v, norm_size, dataset_size);

    // 3. Ray exits at min(brick tFar, ray tEnd).
    let t_brick    = intersect_box(ray_origin, inv_ray_dir, brick_min_n, brick_max_n);
    info.t_end     = min(t_brick.y, t_end_ray);

    // 4. LUT lookup.
    let lut_entry  = textureLoad(t_lut, safe_idx, 0);
    info.lut_entry = lut_entry;
    info.brick_max = textureLoad(t_brick_max, safe_idx, 0).r;
    info.valid     = lut_entry.w > 0u;   // w==0 → not yet loaded

    // 5. If valid, compute step budget.
    if (info.valid) {
        info.lod_scale = get_lod_scale(lut_entry.w);
        let brick_len       = max(info.t_end - t, 1e-6);
        let brick_world_len = length(brick_max_n - brick_min_n);
        let max_scale  = max(info.lod_scale.x, max(info.lod_scale.y, info.lod_scale.z));
        info.num_steps = max(1u, u32((STEPS_PER_BRICK / max_scale) * brick_len / brick_world_len));
        info.step_size = brick_len / f32(info.num_steps);
    }

    return info;
}


// ── MIP brick lookup ──────────────────────────────────────────────────────

// Like setup_brick() but receives t_end and the brick index from the DDA
// caller instead of computing them via intersect_box() / floor(). Eliminates
// both the per-brick slab test and the float boundary ambiguity.
fn lookup_brick_mip(
    t_entry:      f32,
    t_end_dda:    f32,
    entry_idx:    vec3<i32>,  // DDA-maintained brick index (no float floor needed)
    norm_size:    vec3<f32>,
    dataset_size: vec3<f32>,
) -> BrickInfo {
    var info: BrickInfo;

    let block_size = vec3<f32>(u_vol_params.block_size_x,
                               u_vol_params.block_size_y,
                               u_vol_params.block_size_z);
    let lut_size_i = vec3<i32>(i32(u_vol_params.lut_size_x),
                               i32(u_vol_params.lut_size_y),
                               i32(u_vol_params.lut_size_z));

    // 1. Brick index from DDA state — exact, no float boundary ambiguity.
    let safe_idx  = clamp(entry_idx, vec3<i32>(0), lut_size_i - vec3<i32>(1));

    // 2. t_end is supplied by the DDA — no slab test needed.
    info.t_end = t_end_dda;

    // 3. LUT and brick_max lookups (identical to setup_brick).
    let lut_entry  = textureLoad(t_lut, safe_idx, 0);
    info.lut_entry = lut_entry;
    info.brick_max = textureLoad(t_brick_max, safe_idx, 0).r;
    info.valid     = lut_entry.w > 0u;

    // 4. Step budget (identical to setup_brick, using DDA-derived brick length).
    if (info.valid) {
        info.lod_scale = get_lod_scale(lut_entry.w);
        let brick_len       = max(info.t_end - t_entry, 1e-6);
        // brick_world_len: diagonal of one brick in normalized space.
        // Since voxel→norm is a uniform linear scale, this is constant for
        // all bricks — no AABB reconstruction needed.
        let brick_norm_size = norm_size * block_size / dataset_size;
        let brick_world_len = length(brick_norm_size);
        let max_scale       = max(info.lod_scale.x, max(info.lod_scale.y, info.lod_scale.z));
        info.num_steps      = max(1u, u32((STEPS_PER_BRICK / max_scale) * brick_len / brick_world_len));
        info.step_size      = brick_len / f32(info.num_steps);
    }

    return info;
}


// ── Vertex shader ─────────────────────────────────────────────────────────

struct VertexInput {
    @builtin(vertex_index) vertex_index: u32,
};

@vertex
fn vs_main(in: VertexInput) -> Varyings {
    let ns = vec3<f32>(u_vol_params.norm_size_x,
                       u_vol_params.norm_size_y,
                       u_vol_params.norm_size_z);
    let h = ns * 0.5;

    // 8 corners of the normalized box.
    let corners = array<vec3<f32>, 8>(
        vec3<f32>(-h.x, -h.y, -h.z),
        vec3<f32>( h.x, -h.y, -h.z),
        vec3<f32>(-h.x,  h.y, -h.z),
        vec3<f32>( h.x,  h.y, -h.z),
        vec3<f32>(-h.x, -h.y,  h.z),
        vec3<f32>( h.x, -h.y,  h.z),
        vec3<f32>(-h.x,  h.y,  h.z),
        vec3<f32>( h.x,  h.y,  h.z),
    );

    // 12 triangles (36 indices), cull_mode = none.
    let indices = array<u32, 36>(
        0u,2u,1u, 1u,2u,3u,   // -Z face
        4u,5u,6u, 5u,7u,6u,   // +Z face
        0u,1u,4u, 1u,5u,4u,   // -Y face
        2u,6u,3u, 3u,6u,7u,   // +Y face
        0u,4u,2u, 2u,4u,6u,   // -X face
        1u,3u,5u, 3u,7u,5u,   // +X face
    );

    let norm_pos  = corners[indices[in.vertex_index]];
    let world_pos = u_wobject.world_transform * vec4<f32>(norm_pos, 1.0);
    let ndc_pos   = u_stdinfo.projection_transform
                  * u_stdinfo.cam_transform
                  * world_pos;

    let ndc_to_norm = u_wobject.world_transform_inv
                    * u_stdinfo.cam_transform_inv
                    * u_stdinfo.projection_transform_inv;

    let cam_sign = sign(
        u_stdinfo.cam_transform[0][0] *
        u_stdinfo.cam_transform[1][1] *
        u_stdinfo.cam_transform[2][2]
    );

    var varyings: Varyings;
    varyings.position      = vec4<f32>(ndc_pos);
    varyings.world_pos     = vec3<f32>(world_pos.xyz);
    varyings.norm_near_pos = vec4<f32>(ndc_to_norm * vec4<f32>(ndc_pos.xy, -1.0 * cam_sign * ndc_pos.w, ndc_pos.w));
    varyings.norm_far_pos  = vec4<f32>(ndc_to_norm * vec4<f32>(ndc_pos.xy,        cam_sign * ndc_pos.w, ndc_pos.w));
    return varyings;
}


// ── Fragment shader ───────────────────────────────────────────────────────

@fragment
fn fs_main(varyings: Varyings) -> FragmentOutput {
    {$ include 'pygfx.clipping_planes.wgsl' $}

    var out: FragmentOutput;

    let norm_size    = vec3<f32>(u_vol_params.norm_size_x,
                                 u_vol_params.norm_size_y,
                                 u_vol_params.norm_size_z);
    let dataset_size = vec3<f32>(u_vol_params.dataset_size_x,
                                 u_vol_params.dataset_size_y,
                                 u_vol_params.dataset_size_z);
    let iso_threshold = u_material.threshold;

    // ── Ray setup in normalized space ──────────────────────────────────
    let far_pos  = varyings.norm_far_pos.xyz  / varyings.norm_far_pos.w;
    let near_pos = varyings.norm_near_pos.xyz / varyings.norm_near_pos.w;
    let ray_dir  = normalize(far_pos - near_pos);

    // Guard near-zero components to avoid NaN downstream.
    let safe_dir    = select(ray_dir, vec3<f32>(1e-10), abs(ray_dir) < vec3<f32>(1e-10));
    let inv_ray_dir = 1.0 / safe_dir;

    // ── Volume AABB intersection from the near plane ───────────────────
    // Using near_pos (not the box surface) as origin means tNear < 0 when
    // the camera is inside the volume, and max(tNear, 0) clamps to the
    // near plane — correct for both inside and outside cases.
    let half_ns = norm_size * 0.5;
    let hit     = intersect_box(near_pos, inv_ray_dir, -half_ns, half_ns);
    if (hit.x > hit.y) { discard; }

    var t_start = max(hit.x, 0.0);
    let t_end   = hit.y;
    if (t_start >= t_end) { discard; }

    $$ if debug_mode == 'ray_dir'
    // ── Debug: show ray direction as RGB ──────────────────────────────
    out.color = vec4<f32>((ray_dir + 1.0) * 0.5, 1.0);
    out.depth = 0.0;

    $$ else
    // ── Brick traversal ────────────────────────────────────────────────
    // All state variables are declared unconditionally (Metal does not
    // allow variable redefinition across template branches).
    let ray_origin = near_pos;

    var t = t_start;

    // ISO state
    var surface_found = false;
    var surface_pos:  vec3<f32>;
    var surface_density: f32 = 0.0;
    var prev_density: f32 = 0.0;
    var prev_t: f32 = t_start;
    var surface_lut_entry: vec4<u32>;
    var surface_lod_scale: vec3<f32>;
    var surface_step_size: f32 = 0.0;

    // Fix 2: track which brick prev_t belongs to for cross-brick bisection.
    var prev_lut_entry: vec4<u32>;
    var prev_lod_scale: vec3<f32>;
    var brick_boundary_t: f32 = t_start;

    // MIP state
    var max_density: f32 = 0.0;
    var max_pos = vec3<f32>(0.0);

    // LOD debug state (always declared; only used in lod_color mode)
    var lod_debug_color = vec3<f32>(0.0);
    var lod_debug_found = false;

    $$ if render_mode == 'mip'
    // ── DDA state for MIP brick traversal ─────────────────────────────────
    // Brick sizes are uniform in normalized space (the voxel→norm transform
    // is a linear scale), so all grid crossings can be precomputed once.
    let block_size_v = vec3<f32>(u_vol_params.block_size_x,
                                  u_vol_params.block_size_y,
                                  u_vol_params.block_size_z);
    let brick_norm   = norm_size * block_size_v / dataset_size;
    let dda_step_v   = vec3<i32>(select(-1, 1, safe_dir.x >= 0.0),
                                  select(-1, 1, safe_dir.y >= 0.0),
                                  select(-1, 1, safe_dir.z >= 0.0));
    let t_delta      = abs(brick_norm / safe_dir);
    let vol_origin_n = -norm_size * 0.5;
    let start_pos_n  = ray_origin + ray_dir * t_start;
    let lut_size_f   = vec3<f32>(f32(u_vol_params.lut_size_x),
                                  f32(u_vol_params.lut_size_y),
                                  f32(u_vol_params.lut_size_z));
    var dda_idx      = clamp(
        vec3<i32>(floor((start_pos_n - vol_origin_n) / brick_norm)),
        vec3<i32>(0),
        vec3<i32>(lut_size_f) - vec3<i32>(1)
    );
    // For each axis, t at which the ray first exits the starting brick.
    // Positive step → forward face at (idx+1)*brick_norm; negative → idx*brick_norm.
    let face_idx  = vec3<f32>(dda_idx) + select(vec3<f32>(0.0), vec3<f32>(1.0),
                                                 dda_step_v > vec3<i32>(0));
    // dda_t_max holds absolute t-values along the ray (same space as t_start/t_end).
    // (face - start_pos_n) / dir gives the t-offset from t_start, so add t_start.
    var dda_t_max = t_start + (vol_origin_n + face_idx * brick_norm - start_pos_n) / safe_dir;
    $$ endif

    for (var brick_iter = 0u; brick_iter < MAX_BRICK_ITERS; brick_iter++) {
        $$ if render_mode == 'mip'
        if (t >= t_end) { break; }

        // ── DDA advance ────────────────────────────────────────────────────
        // Find which axis the ray exits through first, step the DDA, then
        // look up the brick. This replaces the intersect_box() call inside
        // setup_brick() with three comparisons and one add per brick.
        let cross_x    = dda_t_max.x <= dda_t_max.y && dda_t_max.x <= dda_t_max.z;
        let cross_y    = !cross_x && dda_t_max.y <= dda_t_max.z;
        let cross_axis = select(select(2u, 1u, cross_y), 0u, cross_x);
        let dda_t_exit = min(dda_t_max[cross_axis], t_end);
        let t_entry    = t;
        let entry_idx  = dda_idx;   // save CURRENT brick index before stepping
        t              = dda_t_max[cross_axis];
        dda_t_max[cross_axis] += t_delta[cross_axis];
        dda_idx[cross_axis]   += dda_step_v[cross_axis];
        dda_idx = clamp(dda_idx, vec3<i32>(0), vec3<i32>(lut_size_f) - vec3<i32>(1));

        let brick = lookup_brick_mip(t_entry, dda_t_exit, entry_idx, norm_size, dataset_size);
        $$ else
        if (t >= t_end || surface_found) { break; }

        let brick = setup_brick(ray_origin, ray_dir, inv_ray_dir,
                                t, t_end, norm_size, dataset_size);
        $$ endif

        $$ if debug_mode == 'lod_color'
        if (brick.valid && !lod_debug_found) {
            lod_debug_color = get_lod_color(brick.lut_entry.w);
            lod_debug_found = true;
            break;
        }
        $$ endif

        $$ if render_mode != 'mip'
        // Fix 2: record where this brick begins for cross-brick bisection.
        brick_boundary_t = t;
        $$ endif

        if (!brick.valid) {
            $$ if render_mode == 'mip'
            continue;   // DDA already advanced t; just skip to next brick.
            $$ else
            t = brick.t_end + 0.0001;
            prev_density = 0.0;
            continue;
            $$ endif
        }

        $$ if render_mode == 'mip'
        // MIP early-out: skip bricks whose max can't beat our running maximum.
        if (brick.brick_max <= max_density) { continue; }
        $$ else
        // ISO early-out: skip bricks that are entirely below the isosurface.
        if (brick.brick_max < iso_threshold) {
            t = brick.t_end + 0.0001;
            prev_density = 0.0;
            continue;
        }
        $$ endif

        // Capture for post-loop bisection (ISO only, but always written).
        surface_lut_entry = brick.lut_entry;
        surface_lod_scale = brick.lod_scale;
        surface_step_size = brick.step_size;

        $$ if render_mode == 'mip'
        // Nudge off the exact brick boundary so t_sample never resolves to
        // the degenerate boundary voxel (which fmod can assign to either
        // neighbor depending on floating-point rounding).
        var t_sample = t_entry + brick.step_size * 0.5;
        $$ else
        var t_sample = t;
        $$ endif

        for (var i = 0u; i < brick.num_steps; i++) {
            $$ if render_mode == 'mip'
            if (t_sample > dda_t_exit) { break; }
            $$ else
            if (t_sample > brick.t_end) { break; }
            $$ endif

            let pos     = ray_origin + ray_dir * t_sample;
            let voxel   = norm_to_voxel(pos, norm_size, dataset_size);
            let density = sample_atlas_nearest(voxel, brick.lut_entry, brick.lod_scale);

            $$ if render_mode == 'mip'
            // MIP: track maximum intensity and its position across the ray.
            if (density > max_density) {
                max_density = density;
                max_pos     = pos;
            }
            $$ else
            // ISO: detect threshold crossing.
            if (prev_density < iso_threshold && density >= iso_threshold) {
                surface_found   = true;
                surface_pos     = pos;
                surface_density = density;
                break;
            }
            prev_density = density;
            prev_t       = t_sample;
            // Fix 2: track which brick prev_t belongs to.
            prev_lut_entry = brick.lut_entry;
            prev_lod_scale = brick.lod_scale;
            $$ endif

            t_sample += brick.step_size;
        }

        $$ if render_mode != 'mip'
        if (!surface_found) {
            t = brick.t_end + 0.0001;
        }
        $$ endif
        // MIP: t already advanced by DDA at the top of this iteration.
    }

    // ── Post-traversal output ─────────────────────────────────────────

    $$ if debug_mode == 'lod_color'
    if (!lod_debug_found) { discard; }
    out.color = vec4<f32>(lod_debug_color, 1.0);
    out.depth = 0.0;

    $$ elif render_mode == 'mip'
    // ── MIP output ────────────────────────────────────────────────────
    if (max_density <= 0.0) { discard; }

    let mip_value = vec4<f32>(max_density, 0.0, 0.0, 1.0);
    let mip_color = sampled_value_to_color(mip_value);
    $$ if colorspace == 'srgb'
    let mip_physical = srgb2physical(mip_color.rgb);
    $$ else
    let mip_physical = mip_color.rgb;
    $$ endif

    let mip_opacity = mip_color.a * u_material.opacity;
    do_alpha_test(mip_opacity);

    let world_pos_m = u_wobject.world_transform * vec4<f32>(max_pos, 1.0);
    let ndc_pos_m   = u_stdinfo.projection_transform
                    * u_stdinfo.cam_transform
                    * world_pos_m;

    out.color = vec4<f32>(mip_physical, mip_opacity);
    out.depth = ndc_pos_m.z / ndc_pos_m.w;

    $$ if write_pick
    let mip_pick_coord = (max_pos / norm_size) + vec3<f32>(0.5);
    out.pick = (
        pick_pack(u32(u_wobject.global_id), 20) +
        pick_pack(u32(mip_pick_coord.x * 16383.0), 14) +
        pick_pack(u32(mip_pick_coord.y * 16383.0), 14) +
        pick_pack(u32(mip_pick_coord.z * 16383.0), 14)
    );
    $$ endif

    $$ else
    // ── ISO output ────────────────────────────────────────────────────
    if (!surface_found) { discard; }

    // ── Binary bisection refinement (4 iterations → 16× finer) ────────
    // Fix 2: brick-aware bisection — select the correct atlas slot per probe.
    var lo = prev_t;
    var hi = prev_t + surface_step_size;
    for (var r = 0u; r < 4u; r++) {
        let mid      = (lo + hi) * 0.5;
        let pos_mid  = ray_origin + ray_dir * mid;
        let voxel_m  = norm_to_voxel(pos_mid, norm_size, dataset_size);
        let in_prev  = mid < brick_boundary_t;
        let bis_lut  = select(surface_lut_entry, prev_lut_entry, in_prev);
        let bis_lod  = select(surface_lod_scale, prev_lod_scale, in_prev);
        let d_mid    = sample_atlas_nearest(voxel_m, bis_lut, bis_lod);
        if (d_mid >= iso_threshold) { hi = mid; } else { lo = mid; }
    }
    let refined_t   = (lo + hi) * 0.5;
    let refined_pos = ray_origin + ray_dir * refined_t;

    // ── Gradient-based normal (central differences in voxel space) ────
    // Fix 2: use the atlas slot matching the refined position's brick.
    let grad_in_prev = refined_t < brick_boundary_t;
    let grad_lut     = select(surface_lut_entry, prev_lut_entry, grad_in_prev);
    let grad_lod     = select(surface_lod_scale, prev_lod_scale, grad_in_prev);
    // Offset by ~1.5 voxels at the current LOD level (in finest-level coords).
    let grad_eps    = grad_lod * 1.5;
    let refined_v   = norm_to_voxel(refined_pos, norm_size, dataset_size);

    // Fix 3: compute brick corner once from the refined position so gradient
    // probes that cross a brick boundary use a direct offset rather than fmod,
    // which would remap them into the wrong atlas tile.
    let block_size_v   = vec3<f32>(u_vol_params.block_size_x,
                                   u_vol_params.block_size_y,
                                   u_vol_params.block_size_z);
    let voxel_k_ref    = refined_v / grad_lod;
    let brick_corner_k = floor(voxel_k_ref / block_size_v) * block_size_v;

    let dx = sample_atlas_with_corner(refined_v + vec3<f32>(grad_eps.x, 0.0, 0.0),
                                      grad_lut, grad_lod, brick_corner_k)
           - sample_atlas_with_corner(refined_v - vec3<f32>(grad_eps.x, 0.0, 0.0),
                                      grad_lut, grad_lod, brick_corner_k);
    let dy = sample_atlas_with_corner(refined_v + vec3<f32>(0.0, grad_eps.y, 0.0),
                                      grad_lut, grad_lod, brick_corner_k)
           - sample_atlas_with_corner(refined_v - vec3<f32>(0.0, grad_eps.y, 0.0),
                                      grad_lut, grad_lod, brick_corner_k);
    let dz = sample_atlas_with_corner(refined_v + vec3<f32>(0.0, 0.0, grad_eps.z),
                                      grad_lut, grad_lod, brick_corner_k)
           - sample_atlas_with_corner(refined_v - vec3<f32>(0.0, 0.0, grad_eps.z),
                                      grad_lut, grad_lod, brick_corner_k);
    let gradient = vec3<f32>(dx, dy, dz);
    let normal   = select(normalize(-gradient), vec3<f32>(0.0, 1.0, 0.0),
                          length(gradient) < 1e-6);

    $$ if debug_mode == 'normal_rgb'
    // ── Debug: normal as RGB ───────────────────────────────────────────
    out.color = vec4<f32>((normal + 1.0) * 0.5, 1.0);
    out.depth = 0.0;

    $$ else
    // ── Phong shading ──────────────────────────────────────────────────
    let the_value      = vec4<f32>(surface_density, 0.0, 0.0, 1.0);
    let color          = sampled_value_to_color(the_value);
    $$ if colorspace == 'srgb'
    let physical_color = srgb2physical(color.rgb);
    $$ else
    let physical_color = color.rgb;
    $$ endif

    let view_dir   = normalize(-ray_dir);
    let is_front   = dot(normal, view_dir) > 0.0;
    let lit_color  = lighting_phong(is_front, normal, view_dir, physical_color);

    let opacity = color.a * u_material.opacity;
    do_alpha_test(opacity);

    // ── Depth output ───────────────────────────────────────────────────
    let world_pos_r = u_wobject.world_transform * vec4<f32>(refined_pos, 1.0);
    let ndc_pos_r   = u_stdinfo.projection_transform
                    * u_stdinfo.cam_transform
                    * world_pos_r;

    out.color = vec4<f32>(lit_color, opacity);
    out.depth = ndc_pos_r.z / ndc_pos_r.w;

    $$ if write_pick
    let iso_pick_coord = (refined_pos / norm_size) + vec3<f32>(0.5);
    out.pick = (
        pick_pack(u32(u_wobject.global_id), 20) +
        pick_pack(u32(iso_pick_coord.x * 16383.0), 14) +
        pick_pack(u32(iso_pick_coord.y * 16383.0), 14) +
        pick_pack(u32(iso_pick_coord.z * 16383.0), 14)
    );
    $$ endif
    $$ endif
    $$ endif
    $$ endif

    return out;
}
